# configmap.yaml

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fiberplane-proxy
data:
  data_sources.yaml: |
    # Change this file to point to your actual data source(s)

    # You can add data sources using this format:
    # The data source name will appear in the Fiberplane Studio
    Prometheus: # <-- The name of the data source
      type: prometheus # <-- the type of the data source. for now prometheus only, more data sources coming soon!)
      options: # <-- parameters for the data source (usually just the URL)
        url: http://your-prometheus-server 