# configmap.yaml

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fiberplane-proxy
data:
  data_sources.yaml: |
    # Change this file to point to your actual data source(s)

    # You can add data sources using this format:
    # Data Source Name:
    #   type: prometheus
    #   options:
    #     url: your prometheus URL

    # More data source types are coming soon!

    # The data source name will appear in the Fiberplane Studio
   - name: prometheus-prod
		 description: Prometheus (Production)
		 providerType: prometheus
		 config:
	     # Replace the following line with your Prometheus URL
	     url: http://prometheus