# configmap.yaml

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fiberplane-proxy
data:
  data_sources.yaml: |
    
    # You can add data sources using this format:
    
    My Prometheus server:
      type: prometheus
      url: http://prometheus-server
    
    My Elasticsearch server:
      type: elasticsearch
      url: http://username:password@elastic-server
    
    My Loki server:
      type: loki
      url: http://loki-server:port
