# configmap.yaml

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fiberplane-proxy
data:
  data_sources.yaml: |
    # Change this file to point to your actual data source(s)

    # You can add data sources using this format:
    
    Prometheus: # <-------------------------------------------- Set the name of the data source how it should appear in the Fiberplane Studio
      type: prometheus # <------------------------------------- Set the type of the data source. for now prometheus only, more data sources coming soon!)
      options:  
        url: http://your-prometheus-server # <----------------- Set the URL for the data source