version: '3.9'

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    expose:
      - 9100

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    depends_on:
      - node-exporter

  fp-proxy:
    image: fiberplane/proxy:v1
    container_name: fp-proxy
    restart: unless-stopped
    volumes:
      - ./data_sources.yaml:/app/data_sources.yaml
    command:
      -  --auth-token=${TOKEN:?err}
    depends_on:
      - prometheus
      - node-exporter