- name: starter-prom
  description: Prometheus starterkit
  providerType: prometheus
  config:
    url: http://prometheus:9090

- name: starter-loki
  description: Loki starterkit
  providerType: loki
  config:
    url: http://loki:3100